[project]
name = "hw1"
version = "0.1.0"
description = ""
authors = [
    {name = "dim-papach",email = "102074058+dim-papach@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
"ipykernel",
"jupyter",
"nbformat",
"nbconvert",
"numpy",
"pandas",
"seaborn",
"kagglehub (>=1.0.0,<2.0.0)",
"matplotlib",
"scikit-learn",
"torch",
"pytest (>=9.0.2,<10.0.0)"
]

[tool.poetry]
packages = [{include = "hw1", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
